<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Kecamatan;
class Detail_Laporan extends Model
{
    protected $table='detail_laporans';
    protected $fillable = [
    'id',
    'id_kelurahans', 
    'sumber_data', 
    'desa', 
    'kecamatan', 
    'kabupaten', 
    'provinsi', 
    'jumlah_penduduk', 
    'jumlah_kk', 
    'luas_wilayah', 
    'kepadatan_penduduk', 
    'perpindahan_penduduk', 
    'jumlah_meninggal', 
    'perubahan_data', 
    'wajib_ktp', 
    'islam', 
    'kristen', 
    'katholik', 
    'hindu', 
    'budha', 
    'konghucu', 
    'kepercayaan_terhadap_tuhan_yme', 
    'laki_laki', 
    'perempuan', 
    'belum_kawin', 
    'kawin', 
    'cerai_hidup', 
    'cerai_mati', 
    'usia0_4thn', 
    'usia5_9thn', 
    'usia10_14thn', 
    'usia15_19thn', 
    'usia20_24thn', 
    'usia25_29thn', 
    'usia30_34thn', 
    'usia35_39thn', 
    'usia40_44thn', 
    'usia45_49thn', 
    'usia50_54thn', 
    'usia55_59thn', 
    'usia60_64thn', 
    'usia65_69thn', 
    'usia70_74thn', 
    'usia_75thn_keatas', 
    'lahir_thn_2018', 
    'lahir_sebelum_thn_2018', 
    'pertumbuhan_penduduk_2016', 
    'pertumbuhan_penduduk_2017', 
    'pertumbuhan_penduduk_2018', 
    'usia_sekolah_3_4_thn', 
    'usia_sekolah_5_thn', 
    'usia_sekolah_6_11_thn', 
    'usia_sekolah_12_14_thn', 
    'usia_sekolah_15_17_thn', 
    'usia_sekolah_18_22_thn', 
    'usia_4_18_thn_khusus', 
    'usia_5_6_thn_paud', 
    'usia_7_12_thn_sd', 
    'usia_12_15_thn_smp', 
    'usia_16_18_thn_sma', 
    'tidak_atau_belum_sekolah', 
    'belum_tamat_sd', 
    'tamat_sd', 
    'sltp', 
    'slta', 
    'd1_dan_d2',
    'd3', 
    's1', 
    's2', 
    's3', 
    'goldar_a', 
    'goldar_b', 
    'goldar_ab', 
    'goldar_o', 
    'goldar_a_plus', 
    'goldar_a_min', 
    'goldar_b_plus', 
    'goldar_b_min', 
    'goldar_ab_plus', 
    'goldar_ab_min', 
    'goldar_o_plus', 
    'goldar_o_min', 
    'goldar_tidak_tahu', 
    'belum_atau_tidak_bekerja', 
    'aparatur_pejabat_negara', 
    'tenaga_pengajar', 
    'wiraswasta', 
    'pertanian_dan_peternakan', 
    'nelayan', 
    'agama_dan_kepercayaan', 
    'pelajar_dan_mahasiswa', 
    'tenaga_kesehatan', 
    'pensiunan', 
    'pekerjaan_lainnya', 
    'tahun',
    'semester'
    ];
 

    public function kecamatan()
    {
        return $this->belongsTo(Kecamatan::class,'id_kelurahans');
    }
    
}
